config/routes.rb
Rails.application.routes.draw do

  root :to =>'jokes#index'
  resources :jokes do
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jokes
  validates :name, :presence => true

end

app/models/joke.rb
class Joke < ActiveRecord::Base
  belongs_to :category
  validates :question, :presence => true
  validates :punchline, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController

before_action :find_joke, only: [:show, :edit, :update, :destroy]


	def index
		if params[:category].blank?
		@jokes = Joke.all.order("created_at DESC")
		else
		@category_id = Category.find_by(name: params[:category]).id
		@jokes =Joke.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@joke = Joke.new
	end

	def create
		@joke = Joke.new(joke_params)
		if @joke.save
	  redirect_to jokes_path
	  else
	    render :new
	  end
	end

	def edit
  end

  def update
		if @joke.update(joke_params)
			redirect_to jokes_path
		else
			render :edit
  	end
	end

  def destroy
    @joke.destroy
    redirect_to root_path
  end

  private
  def joke_params
    params.require(:joke).permit(:question, :punchline,  :category_id)
  end
	def find_joke
		@joke = Joke.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jokes/_form.html.erb
<%= render "layouts/errors", :object => @joke %>

<%= simple_form_for(@joke, html: {class: 'form-horizontal new-form'}) do |f| %>
  <%= f.collection_select :category_id, Category.all, :id, :name,  {prompt: "chose a category"} %>
  <%= f.label :question %>
  <%= f.text_field :question %>
  <%= f.label :punchline %>
  <%= f.text_field :punchline %>
  <%= f.submit %>
<% end %>

app/views/jokes/edit.html.erb
<% content_for :title, "Joss Monster | New Skill" %>

<h1 class="form-titles">Edit Joke</h1>

<%= render "form" %>

<%= link_to "Back", root_path %>

app/views/jokes/index.html.erb
<% content_for :title, "Dad Jokes | Home" %>


<div class="container">
<div class="row">
		<div class="col-lg-6">
	  <% @jokes.each do |joke| %>
	     <p><%= link_to joke.question, joke_path(joke) %></p>
	  <% end %>


	</div><!-- end of col 3 -->
		<div class="col-lg-6">
			<div class="center-block test-center">
				<p class="ron-text">Do I need to remind you</p>
				<%= image_tag("ronb.jpeg", :alt => "ron burgendy", :class => "img-responsive center-block") %>
				<p class="ron-text">to keep it classy?</p>

		<div class="text-center"><button class="btn btn-default"><%= link_to "Add a joke", new_joke_path %></button></div>
		</div>
	</div><!-- end of row 2 -->
</div><!-- end of main container -->

app/views/jokes/new.html.erb
<% content_for :title, "Joss Monster | New Joke" %>

<h1 class="form-titles">New Joke</h1>

<%= render "form" %>

<%= link_to "Back", root_path %>

app/views/jokes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="well">
        <p><%= @joke.question %></p>
        <p><%= @joke.punchline %></p>
      </div>
      <button class="btn btn-default"><%= link_to "Edit a joke", edit_joke_path(@joke) %></button>
      <button class="btn btn-default"><%= link_to "Delete joke", joke_path(@joke),
      :data => {:confirm => "Do you really want to delete this classic?", :method => "delete"} %></button>
      <br>
      <br>
      <p><%= link_to "Back Home", root_path %></p>
  </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>These errors need fixed:</h3>
  <ul class="errors">
    <% object.errors.full_messages.each do |message| %>
      <li ><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" id="my-navbar">
      <div class="container">
        <div class="navbar-header">

          <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>

          <a href="/jokes" class="navbar-brand">Dad Jokes: John vs. Diego</a>

        </div><!-- end of navbar header div -->
         <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
          <% Category.all.each do |category| %>
          <li><%= link_to category.name, jokes_path(category: category.name) %></li>
          <% end %>
        </ul>
          <a class="btn btn-default navbar-btn navbar-right" href="#">Login</a>
          <a class="btn btn-default navbar-btn navbar-right" href="/jokes/new">Add a Joke</a>

        </div><!-- end of nav that contains ul links -->

      </div><!--end of nav container -->
    </nav><!-- End navbar -->

<div class="container">

  <%= yield %>
</div>
</body>
</html>